services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: snack_website
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5430:5432" 
    volumes:
      # - pgdata:/var/lib/postgresql/data
      #- pgdata:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
