services:
  backend:
    build: .
    container_name: spring_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/snack_website
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: snack_website
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5430:5432" 
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata:
